gutter-sales-assist/main/default/objects/CalloutLog__c/CalloutLog__c.object-meta.xml
<CustomObject>
    <description>Logs response from various HTTP requests.</description>
    <label>CalloutLog</label>
    <nameField>
        <label>CalloutLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CalloutLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gutter-sales-assist/main/default/objects/CalloutLog__c/fields/RequestDateTime__c.field-meta.xml
<CustomField>
    <fullName>RequestDateTime__c</fullName>
    <description>Date/Time request was made.</description>
    <label>RequestDateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

gutter-sales-assist/main/default/objects/CalloutLog__c/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <description>The HTTP response body.</description>
    <label>ResponseBody</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

gutter-sales-assist/main/default/objects/CalloutLog__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>HTTP response status code.</description>
    <label>StatusCode</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

gutter-sales-assist/main/default/classes/repositories/CalloutLogRepository.cls
public with sharing class CalloutLogRepository implements ICalloutLogRepository {
    public void logResponse(HttpResponse response) {
        CalloutLog__c calloutLog = getCalloutLogFromResponse(response);

        insert calloutLog;
    }

    public void logResponses(List<HttpResponse> responses) {
        List<CalloutLog__c> calloutLogs = new List<CalloutLog__c>();
        for (HttpResponse response : responses) {
            calloutLogs.add(getCalloutLogFromResponse(response));
        }

        insert calloutLogs;
    }

    private CalloutLog__c getCalloutLogFromResponse(HttpResponse response) {
        CalloutLog__c calloutLog = new CalloutLog__c(
            RequestDateTime__c = DateTime.now(),
            StatusCode__c = String.valueOf(response.getStatusCode()),
            ResponseBody__c = response.getBody()
        );

        return calloutLog;
    }
}